export const UPDATE_BUILDINGS = 'UPDATE_BUILDINGS';
export const SET_KINGDOM = 'SET_KINGDOM';
export const UPDATE_RESOURCES = 'UPDATE_RESOURCE';
export const UPDATE_RESOURCES_SUCCESS = 'UPDATE_RESOURCE_SUCCESS';
export const UPDATE_RESOURCES_FAILURE = 'UPDATE_RESOURCE_FAILURE';
export const UPDATE_TROOPS = 'UPDATE_TROOPS';
export const SET_USER = 'SET_USER';
