name: Frontend CI

on:
  pull_request:
    paths:
    - 'frontend/**'

env:
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: yarn install
      working-directory: ./frontend
    - name: Build
      run: yarn build
      working-directory: ./frontend
    - name: Run Tests
      run: yarn test
      working-directory: ./frontend
